Name:           ros-lunar-urdf-tutorial
Version:        0.2.5
Release:        0%{?dist}
Summary:        ROS urdf_tutorial package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/urdf_tutorial
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-controller-manager
Requires:       ros-lunar-diff-drive-controller
Requires:       ros-lunar-gazebo-ros
Requires:       ros-lunar-gazebo-ros-control
Requires:       ros-lunar-joint-state-controller
Requires:       ros-lunar-joint-state-publisher
Requires:       ros-lunar-position-controllers
Requires:       ros-lunar-robot-state-publisher
Requires:       ros-lunar-rqt-robot-steering
Requires:       ros-lunar-rviz
Requires:       ros-lunar-urdf
Requires:       ros-lunar-xacro
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-roslaunch

%description
This package contains a number of URDF tutorials.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Fri Apr 28 2017 David V. Lu!! <davidvlu@gmail.com> - 0.2.5-0
- Autogenerated by Bloom

